verbose = false                         # can be true or false - default is false
blockchain = "mainnet"                  # can be "mainnet", "testnet", "stn", "regtest" - default is "mainnet"

[block_archive]                         # configuration for the BlockArchive
enabled = true                          # whether the component is enabled, default is true
root_path = "/mnt/local/data/mainnet"   # REQUIRED: the root path for the Simple File Block Archive

[chain_store]                           # configuration for the ChainStore
enabled = true                          # whether the component is enabled, default is true
root_path = "bsvmain"                   # the root directory in foundationdb - the default value depends on the
                                        # blockchain configuration and is one of "bsvmain", "bsvtest", "bsvstn", "bsvregtest"
                                        # sub-directories should be split by a "/", initial and final "/" are not required

